[workspace.package]
authors = ["RegionX <support@regionx.tech>"]
edition = "2021"
repository = "https://github.com/RegionX-Labs/CorespaceWeigher.git"
license = "GPL-3.0-only"

[workspace]
members = [
    "bin/server",
    "bin/tracker",
    "routes",
    "shared",
    "types",
]
