output_directory = "out/"
registry = "registry.json"

#[payment_info]
#rpc_url = "wss://rococo-rpc.polkadot.io"
#receiver = "5DADsnBXr5DXiEAjdJvruf6c7ZSUR8iXUTATQqJfheGLiEVm"
#cost = "1000000000" #0.001 ROC
